{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.bo3-server;

  serverDeps = with pkgs; [
    steamcmd
    wineWowPackages.stable
    winetricks
    curl
    wget
    unzip
    steam-run
  ];

  # Generate server configuration file
  serverConfig = pkgs.writeText "server.cfg" ''
    // Server Configuration - Generated by NixOS
    set live_steam_server_name "${cfg.serverName}"
    set live_steam_server_description "${cfg.description}"

    // Non-Gameplay Configuration
    set com_maxclients "${toString cfg.maxClients}"
    set lobby_min_players "${toString cfg.lobbyMinPlayers}"
    ${optionalString (cfg.rconPassword != "") ''set rcon_password "${cfg.rconPassword}"''}
    ${optionalString (cfg.password != "") ''set g_password "${cfg.password}"''}
    set sv_privateClients "0"
    set sv_timeout "30"
    set sv_reconnectlimit "3"
    set sv_pure "0"
    set sv_floodProtect "${if cfg.floodProtect then "1" else "0"}"
    set g_log "boiii/server.log"
    set sv_lobby_mode "${cfg.gameMode}"
    set sv_skip_lobby "${if cfg.skipLobby then "1" else "0"}"
    set sv_lanonly "${if cfg.lanOnly then "1" else "0"}"
    set g_logsync 2

    // Base Game Configuration
    exec "gamedata/gamesettings/${cfg.gameMode}/gamesettings_default.cfg"
    ${optionalString (cfg.gameMode == "zm" || cfg.gameMode == "cp")
    ''exec "gamedata/configs/common/default_xboxlive.cfg"''}
    exec "gamedata/gamesettings/${cfg.gameMode}/gamesettings_${
      (builtins.head cfg.mapRotation).gametype
    }.cfg"

    // Game Settings
    set cg_thirdPerson "0"
    set g_deadChat "${if cfg.deadChat then "1" else "0"}"
    ${optionalString (cfg.gameMode == "zm") ''set scr_firstGumFree "${if cfg.firstGumFree then "1" else "0"}"''}

    // Bot Settings (MP only)
    ${optionalString (cfg.gameMode == "mp") ''
    set bot_difficulty ${toString cfg.botDifficulty}
    set bot_minplayers ${toString cfg.botMinPlayers}
    set g_allowVote ${if cfg.allowVote then "1" else "0"}
    set scr_game_killcam ${if cfg.killcam then "1" else "0"}
    ''}

    // Extra Configuration
    ${cfg.extraConfig}

    // Map Rotation
    set sv_maprotation "${
      concatStringsSep " "
      (map (m: "gametype ${m.gametype} map ${m.map}") cfg.mapRotation)
    }"
  '';

  # Server directory (where the actual game files are)
  serverDir = "${cfg.dataDir}/UnrankedServer";

  # Launch script
  launchScript = pkgs.writeShellScriptBin "bo3-server-launch" ''
    set -euo pipefail

    export PATH="${lib.makeBinPath serverDeps}:$PATH"
    export WINEPREFIX="${cfg.dataDir}/.wine"
    export HOME="${cfg.dataDir}"

    # Change to the UnrankedServer directory where the game files are
    cd "${serverDir}"

    # Determine executable based on client type
    case "${cfg.client}" in
      boiii)
        EXE="boiii.exe"
        ;;
      t7x)
        EXE="t7x.exe"
        ;;
      official)
        EXE="BlackOps3_UnrankedDedicatedServer.exe"
        ;;
    esac

    ARGS="-headless"
    ARGS="$ARGS +set net_port ${toString cfg.port}"
    ARGS="$ARGS +set logfile 2"
    ${optionalString (cfg.modId != "")
    ''ARGS="$ARGS +set fs_game ${cfg.modId}"''}

    # Determine config file based on gameMode if not explicitly set
    ${if cfg.configFile != null then ''
      ARGS="$ARGS +exec ${cfg.configFile}"
    '' else ''
      # Select config filename based on gameMode and copy generated config
      ${if cfg.gameMode == "zm" then ''
        cp -f ${serverConfig} "${serverDir}/zone/server_zm.cfg"
        ARGS="$ARGS +exec server_zm.cfg"
      '' else if cfg.gameMode == "cp" then ''
        cp -f ${serverConfig} "${serverDir}/zone/server_cp.cfg"
        ARGS="$ARGS +exec server_cp.cfg"
      '' else ''
        cp -f ${serverConfig} "${serverDir}/zone/server.cfg"
        ARGS="$ARGS +exec server.cfg"
      ''}
    ''}

    exec ${pkgs.steam-run}/bin/steam-run \
      ${pkgs.wineWowPackages.stable}/bin/wine \
      "$EXE" $ARGS
  '';

  # Installation script
  installScript = pkgs.writeShellScriptBin "bo3-server-install" ''
    set -euo pipefail

    export PATH="${lib.makeBinPath serverDeps}:$PATH"
    export WINEPREFIX="${cfg.dataDir}/.wine"
    export HOME="${cfg.dataDir}"

    echo "=== Black Ops 3 Server Installation ==="
    echo "Installing to: ${cfg.dataDir}"
    echo ""

    mkdir -p "${cfg.dataDir}"
    cd "${cfg.dataDir}"

    if [ -z "${cfg.steamUser}" ]; then
      echo "Error: services.bo3-server.steamUser must be set"
      exit 1
    fi

    echo "=== Downloading server files via SteamCMD ==="
    echo "You will be prompted for your Steam password."
    echo ""

    ${pkgs.steam-run}/bin/steam-run ${pkgs.steamcmd}/bin/steamcmd \
      +@sSteamCmdForcePlatformType windows \
      +force_install_dir "${cfg.dataDir}" \
      +login "${cfg.steamUser}" \
      +app_update 545990 validate \
      +quit

    echo ""
    echo "=== Downloading custom clients ==="

    if [ "${cfg.client}" = "boiii" ] || [ "${cfg.client}" = "all" ]; then
      echo "Downloading EZZBOIII..."
      ${pkgs.curl}/bin/curl -L -o boiii.exe \
        "https://github.com/Ezz-lol/boiii-free/releases/latest/download/boiii.exe" || \
        echo "Warning: Failed to download EZZBOIII"
    fi

    if [ "${cfg.client}" = "t7x" ] || [ "${cfg.client}" = "all" ]; then
      echo "Downloading T7X..."
      ${pkgs.curl}/bin/curl -L -o t7x.exe \
        "https://master.bo3.eu/t7x_v2/t7x.exe" || \
        echo "Warning: Failed to download T7X"
    fi

    echo ""
    echo "=== Copying client executables to server directory ==="
    # SteamCMD installs to UnrankedServer, so copy clients there
    if [ -f "${cfg.dataDir}/boiii.exe" ]; then
      cp -f "${cfg.dataDir}/boiii.exe" "${serverDir}/boiii.exe"
      echo "Copied boiii.exe to server directory"
    fi
    if [ -f "${cfg.dataDir}/t7x.exe" ]; then
      cp -f "${cfg.dataDir}/t7x.exe" "${serverDir}/t7x.exe"
      echo "Copied t7x.exe to server directory"
    fi

    echo ""
    echo "=== Initializing Wine prefix ==="
    ${pkgs.wineWowPackages.stable}/bin/wineboot --init

    echo ""
    echo "=== Creating directory structure ==="
    mkdir -p "${cfg.dataDir}/zone"
    mkdir -p "${serverDir}/zone"

    echo ""
    echo "=== Installation complete ==="
    echo ""
    echo "Start the server with: systemctl start bo3-server"
  '';

in {
  options.services.bo3-server = {
    enable = mkEnableOption "Black Ops 3 dedicated server";

    dataDir = mkOption {
      type = types.path;
      default = "/var/lib/bo3-server";
      description = "Directory where server files are stored";
    };

    user = mkOption {
      type = types.str;
      default = "bo3server";
      description = "User account under which the server runs";
    };

    group = mkOption {
      type = types.str;
      default = "bo3server";
      description = "Group under which the server runs";
    };

    client = mkOption {
      type = types.enum [ "boiii" "t7x" "official" "all" ];
      default = "boiii";
      description =
        "Which client to use (boiii, t7x, official, or all for installation)";
    };

    steamUser = mkOption {
      type = types.str;
      default = "";
      description =
        "Steam username for downloading server files (required for installation)";
    };

    port = mkOption {
      type = types.port;
      default = 27017;
      description = "Game server port";
    };

    serverName = mkOption {
      type = types.str;
      default = "^5NixOS ^7Black Ops 3 Server";
      description = "Server name displayed in server browser";
    };

    description = mkOption {
      type = types.str;
      default = "Powered by NixOS";
      description = "Server description";
    };

    maxClients = mkOption {
      type = types.int;
      default = 18;
      description = "Maximum number of players";
    };

    lobbyMinPlayers = mkOption {
      type = types.int;
      default = 1;
      description = "Minimum players required for match to start";
    };

    password = mkOption {
      type = types.str;
      default = "";
      description = "Server password (empty for public)";
    };

    rconPassword = mkOption {
      type = types.str;
      default = "";
      description = "RCON password for remote administration";
    };

    modId = mkOption {
      type = types.str;
      default = "";
      description = "Steam Workshop mod ID to load";
    };

    botDifficulty = mkOption {
      type = types.ints.between 0 3;
      default = 1;
      description = "Bot difficulty (0=easy, 1=normal, 2=hard, 3=veteran)";
    };

    botMinPlayers = mkOption {
      type = types.int;
      default = 0;
      description = "Minimum players to fill with bots";
    };

    allowVote = mkOption {
      type = types.bool;
      default = true;
      description = "Allow players to vote";
    };

    killcam = mkOption {
      type = types.bool;
      default = true;
      description = "Enable killcam";
    };

    floodProtect = mkOption {
      type = types.bool;
      default = true;
      description = "Enable flood protection";
    };

    deadChat = mkOption {
      type = types.bool;
      default = true;
      description = "Allow dead players' chat to be seen by everyone";
    };

    firstGumFree = mkOption {
      type = types.bool;
      default = true;
      description = "First Gobblegum is free (zombies only)";
    };

    skipLobby = mkOption {
      type = types.bool;
      default = true;
      description =
        "Skip lobby and load map immediately (required for dedicated servers to accept connections)";
    };

    lanOnly = mkOption {
      type = types.bool;
      default = false;
      description =
        "Keep server from broadcasting to public list (LAN/Tailscale only)";
    };

    gameMode = mkOption {
      type = types.enum [ "mp" "zm" "cp" ];
      default = "mp";
      description =
        "Game mode: mp (multiplayer), zm (zombies), cp (campaign/coop)";
    };

    mapRotation = mkOption {
      type = types.listOf (types.submodule {
        options = {
          gametype = mkOption {
            type = types.str;
            description = "Game type (e.g., tdm, dom, ctf)";
          };
          map = mkOption {
            type = types.str;
            description = "Map name (e.g., mp_biodome)";
          };
        };
      });
      default = [
        {
          gametype = "tdm";
          map = "mp_biodome";
        }
        {
          gametype = "tdm";
          map = "mp_spire";
        }
        {
          gametype = "dom";
          map = "mp_sector";
        }
        {
          gametype = "dom";
          map = "mp_apartments";
        }
      ];
      description = "Map rotation list";
    };

    configFile = mkOption {
      type = types.nullOr types.str;
      default = null;
      description =
        "Custom config file to use instead of generated one (e.g., server.cfg, server_zm.cfg)";
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = "Extra configuration lines to add to server.cfg";
    };

    openFirewall = mkOption {
      type = types.bool;
      default = false;
      description = "Open firewall ports for the server";
    };
  };

  config = mkIf cfg.enable {
    # Create user and group
    users.users.${cfg.user} = {
      isSystemUser = true;
      group = cfg.group;
      home = cfg.dataDir;
      createHome = true;
      description = "Black Ops 3 server user";
    };

    users.groups.${cfg.group} = { };

    # Systemd service
    systemd.services.bo3-server = {
      description = "Black Ops 3 Dedicated Server";
      wantedBy = [ "multi-user.target" ];
      after = [ "network.target" ];

      serviceConfig = {
        Type = "simple";
        User = cfg.user;
        Group = cfg.group;
        WorkingDirectory = serverDir;
        ExecStart = "${launchScript}/bin/bo3-server-launch";
        Restart = "on-failure";
        RestartSec = 10;

        # Hardening
        NoNewPrivileges = true;
        PrivateTmp = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        ReadWritePaths = [ cfg.dataDir serverDir ];
      };
    };

    # Installation service (one-shot, manual trigger)
    systemd.services.bo3-server-install = {
      description = "Black Ops 3 Server Installation";
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];

      serviceConfig = {
        Type = "oneshot";
        User = cfg.user;
        Group = cfg.group;
        WorkingDirectory = cfg.dataDir;
        ExecStart = "${installScript}/bin/bo3-server-install";
        StandardInput = "tty-force";
        StandardOutput = "inherit";
        StandardError = "inherit";
        TTYPath = "/dev/tty1";
        TTYReset = true;
        TTYVHangup = true;
      };
    };

    # Firewall rules
    networking.firewall = mkIf cfg.openFirewall {
      allowedUDPPorts = [ cfg.port ];
      allowedTCPPorts = [ cfg.port ];
    };

    # Make install script available system-wide
    environment.systemPackages = [ installScript launchScript ];
  };
}
